const EXTERNAL_API_URL = 'https://api.nomoreparties.co';
// const INTERNAL_API_URL = 'https://api.movies.pyatlina.nomoredomains.work';
const INTERNAL_API_URL = 'http://localhost:3001';

const SHORT_FILM_DURATION = 40;

const FILMS_COUNT_FOR_LARGE_SCREEN = 12;
const FILMS_COUNT_FOR_MIDDLE_SCREEN = 8;
const FILMS_COUNT_FOR_SMALL_SCREEN = 5;

const ADD_MORE_FILMS_FOR_LARGE_SCREEN = 3;
const ADD_MORE_FILMS_FOR_SMALL_SCREEN = 2;

module.exports = {
  EXTERNAL_API_URL,
  // export const INTERNAL_API_URL,
  INTERNAL_API_URL,
  SHORT_FILM_DURATION,
  FILMS_COUNT_FOR_LARGE_SCREEN,
  FILMS_COUNT_FOR_MIDDLE_SCREEN,
  FILMS_COUNT_FOR_SMALL_SCREEN,
  ADD_MORE_FILMS_FOR_LARGE_SCREEN,
  ADD_MORE_FILMS_FOR_SMALL_SCREEN,
}